services:

  nginx:
    container_name: nginx
    environment:
      MOLGENIS_HOST: ${MOLGENIS_HOST:-localhost}
    image: nginx
    links:
      - "molgenis:molgenis"
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 80:80
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build:/usr/share/nginx/html

  molgenis:
    container_name: molgenis
    depends_on:
      - postgresql
      - elasticsearch
      - minio
      - opencpu
    environment:
      - molgenis.home=/home/molgenis
      - opencpu.uri.host=opencpu
      - elasticsearch.transport.addresses=elasticsearch:9300
      - db_uri=jdbc:postgresql://postgresql/molgenis
      - db_user=molgenis
      - db_password=molgenis
      - admin.password=admin
      - MINIO_BUCKET_NAME=molgenis
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=molgenis
      - MINIO_SECRET_KEY=molgenis
      - "CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
    image: registry.molgenis.org/molgenis/molgenis-app:dev
    links:
      - "elasticsearch:elasticsearch"
      - "minio:minio"
      - "opencpu:opencu"
      - "postgresql:postgresql"
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 8080:8080

  postgresql:
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:11-alpine
    ports:
      - 5432:5432
    network_mode: ${NETWORK_MODE:-bridge}
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    environment:
      - cluster.name=molgenis
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  minio:
    command: server /data
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    image: minio/minio:RELEASE.2019-03-20T22-38-47Z
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 9000:9000
    volumes:
      - minio:/data

  opencpu:
    container_name: opencpu
    image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 8004:8004
      - 8787:8787
    volumes:
      - ./opencpu/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./opencpu/ports.conf:/etc/apache2/ports.conf

version: "3.8"
volumes:
  elasticsearch:
  minio:
  postgresql:
