version: "3.7"
services:
  nginx:
    image: nginx
    environment:
      MOLGENIS_HOST: ${MOLGENIS_HOST:-localhost}
    container_name: nginx
    ports:
      - 80:80
    network_mode: ${NETWORK_MODE:-bridge}
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build:/usr/share/nginx/html
  molgenis:
    image: ${MOLGENIS_REPOSITORY}:${MOLGENIS_TAG}
    container_name: molgenis
    network_mode: ${NETWORK_MODE:-bridge}
    environment:
      - molgenis.home=/home/molgenis
      - opencpu.uri.host=opencpu
      - elasticsearch.transport.addresses=elasticsearch:9300
      - db_uri=jdbc:postgresql://postgres/molgenis
      - db_user=molgenis
      - db_password=molgenis
      - admin.password=admin
      - MINIO_BUCKET_NAME=molgenis
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=molgenis
      - MINIO_SECRET_KEY=molgenis
      - "CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    network_mode: ${NETWORK_MODE:-bridge}
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    container_name: elasticsearch
    environment:
      - cluster.name=molgenis
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    network_mode: ${NETWORK_MODE:-bridge}

  minio:
    image: minio/minio:RELEASE.2019-03-20T22-38-47Z
    container_name: minio
    volumes:
      - ~/.molgenis/minio/:/data
    ports:
      - 9000:9000
    network_mode: ${NETWORK_MODE:-bridge}
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    command: server /data

  opencpu:
    image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
    container_name: opencpu
    ports:
      - 8004:8004
      - 8787:8787
    network_mode: ${NETWORK_MODE:-bridge}
    volumes:
      - ./opencpu/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./opencpu/ports.conf:/etc/apache2/ports.conf

volumes:
  db-data:
  es-data:
