<component>
    <span>
        <div
            :title="$t('action-cut')"
            class="btn-tooltip-wrapper"
            v-b-tooltip.d500
        >
            <b-btn
                :disabled="!canCut"
                @click="selectClipboardResources('CUT')"
                variant="secondary"
            >
                <Icon
                    :class="{'fa-disabled' : !canCut}"
                    icon="cut"
                    size="lg"
                />
            </b-btn>
        </div>&nbsp;
        <div
            v-b-tooltip.d500
            class="btn-tooltip-wrapper"
            :title="$t('action-copy')"
        >
            <b-btn
                :disabled="!canCopy"
                variant="secondary"
                @click="selectClipboardResources('COPY')"
            >
                <Icon
                    :class="{'fa-disabled' : !canCopy}"
                    icon="clone"
                    size="lg"
                />
            </b-btn>
        </div>&nbsp;
        <div
            v-b-tooltip.d500
            class="btn-tooltip-wrapper"
            :title="$t('action-paste')"
        >
            <b-btn
                :disabled="!canPaste"
                variant="secondary"
                @click="pasteClipboardResources"
            >
                <Icon
                    :class="{'fa-disabled' : !canPaste}"
                    icon="paste"
                    size="lg"
                />
            </b-btn>
        </div>&nbsp;
    </span>
</component>
